python-hydro/pyro2

- advection/simulation.py
> Fixed typo in comment

- docs/source/compressible_basics.rst
- docs/source/design.rst
- docs/source/incompressible_basics.rst
- docs/source/installation.rst
- docs/source/intro.rst
- docs/source/mesh_basics.rst
- docs/source/multigrid_basics.rst
- docs/source/output.rst
- docs/source/problems.rst
- docs/source/running.rst
Mostly minor typos or the like.
Note removal of duplicate `f2py` in installation instructions, and some added content/links in (in particular) the multigrid section.
> Sphinx docs check

- paper/paper.md
> ORCID update for IH, AH

- mesh/mesh-examples.ipynb
> Fix method name

- docs/notes.txt
- docs/source/conf.py
- docs/source/pyro.advection_rk.problems.rst
- docs/source/pyro.advection_weno.problems.rst
- docs/source/pyro.compressible.rst
- docs/source/pyro.compressible_fv4.problems.rst
- docs/source/pyro.compressible_rk.problems.rst
- docs/source/pyro.compressible_sdc.problems.rst
- docs/write_param_tables.py
sphinx-apidoc should be run with `-l` to follow symlinks
> Update documentation tooling

- .github/workflows/isort.yml
Show what changes need to be made if imports aren't sorted correctly.
> Improve isort error messages

- pyro/analysis/convergence.py
it was saying this is the L2 norm
> fix printout from convergence.py

- pyro/plot.py
if we are plotting the curl or divergence of a field, we need the ghost cells to be valid to get reasonable values
> have plot.py fill ghost cells

- docs/source/conf.py
- docs/source/refs.bib
It seems one of the docs links is broken, or moved to a different server. This PR fixes it.
> Solving docs issue

- pyro/util/plot_tools.py
changed from rounding down to rounding up. Rounding down doesn't seem to work, say when we want to plot 5 or 7 figures.
> fix plot_tools

- pyro/multigrid/derive_analytic_solutions.ipynb
this was still set on python 2 as the interpreter
> rerun notebook

- pyro/mesh/face-centered-data-examples.ipynb
- pyro/mesh/mesh-examples.ipynb
we no longer deal with python 2.x
> remove "from __future__"

- README.md
We're currently only testing with 3.9 and up.
> Bump the required Python version in the readme

- .github/workflows/codespell.yml
- pyro/compressible/unsplit_fluxes.py
we were targeting the wrong branch for PRs
> fix codespell CI

- pyro/pyro_sim.py
this makes things easier when working in Jupyter
> add a get_grid() method to the Pyro class

- pyro/compressible/problems/rt.py
> make the RT problem initial conditions symmetric

- docs/source/conf.py
- docs/source/multigrid.rst
- requirements.txt
> enable dollarmath

- .zenodo.json
- docs/source/ack.rst
> add Zhi and Eric to the .zenodo file

- pyro/compressible/problems/inputs.gresho
for low Mach stuff, we need more steps
> bump up the max steps for gresho

- pyro/compressible/interface.py
divu in spherical is 1/r^2 d/dr(r^2 * u).
> derivative bug fix in divu calculation

- docs/source/compressible-rt-compare.ipynb
> remove one more "do_io=0" from the docs

- pyro/compressible/problems/gresho.py
- pyro/compressible/problems/inputs.gresho
compute ambient pressure from M
> change gresho to take desired Mach number as input

- pyro/compressible/problems/gresho.py
- pyro/compressible/problems/inputs.gresho
inputs parameters are not case sensitive, so change the name to mach
also we were missing the 1/2 in the p0 initialization
> fix gresho mach

- pyro/compressible/derives.py
- pyro/util/io_pyro.py
also add vorticity to compressible derives
> restore derived variables when we read a .h5 file

- examples/mesh/bc_demo.py
- pyro/advection_fv4/fluxes.py
- pyro/compressible_fv4/fluxes.py
- pyro/mesh/__init__.py
- pyro/mesh/fourth_order.py
this is consistent with the other reconstruction routines
> move the 4th order reconstruction into mesh

- pyro/compressible/simulation.py
this catches negative density and internal energy
if these become a problem, then the solution is to do a dual energy formulation or to introduce some floors.
> add some asserts to the compressible solver

- pyro/compressible/problems/inputs.convection
now we only output based on simulation time
> update the convection I/O defaults

- .github/workflows/pytest-mac.yml
this doesn't cover the notebooks
> add Mac OS CI
