python-hydro/pyro2

compressible/BC.py, compressible/problems/__init__.py, compressible/problems/_ramp.defaults, compressible/problems/inputs.ramp, compressible/problems/ramp.py, compressible/simulation.py
Add double Mach reflection problem to compressible solver as ramp.
ramp.py, inputs.ramp, _ramp.defaults are created to set up the initial condition for the problem.
And a specific user-defined boundary condition for this problem is also added to BC.py.
=> Add double Mach reflection problem to compressible solver as ramp.

paper/paper.md
=> Fixing `\star`

advection/simulation.py, advection_nonuniform/simulation.py, analysis/plotvar.py, compressible/simulation.py, compressible_react/simulation.py, diffusion/simulation.py, examples/multigrid/mg_test_general_alphabeta_only.py, examples/multigrid/mg_test_general_beta_only.py, examples/multigrid/mg_test_general_constant.py, examples/multigrid/mg_test_general_dirichlet.py, examples/multigrid/mg_test_general_inhomogeneous.py, examples/multigrid/mg_test_vc_constant.py, examples/multigrid/mg_test_vc_dirichlet.py, examples/multigrid/mg_test_vc_periodic.py, swe/simulation.py
Hi there,
This is in reference to #84. 
For one, `cb.formatter = matplotlib.ticker.FormatStrFormatter("")` prevents a bug in matplotlib where it expects a formatter attribute. The current format does not break the animation but you will see it if you click a chart while it is running and look in your terminal. It adds x and y axis data related to the chart as well as an []. The empty array has data by default that is quite meaningless so `FormatStrFormatter("")` gets rid of the data inside.
My first instinct to fix this was this: `img = plt.imshow(np.transpose(var.v()),` and `plt.colorbar(img)` because of [this stack overflow page](https://stackoverflow.com/questions/2643953/attributeerror-while-adding-colorbar-in-matplotlib). I kept this change in code as it looks to be a best practice …
=> Bug fix - error when hovering pop up window

advection/simulation.py, advection_nonuniform/simulation.py, compressible/simulation.py, compressible_react/simulation.py, compressible_sr/simulation.py, diffusion/simulation.py, incompressible/simulation.py, lm_atm/simulation.py, swe/simulation.py
=> the legacy_colorbar matplotlib option doesn't exist in mpl 3.1 or earlier

.github/workflows/regtest.yml, pyro/pyro_sim.py, pyro/test.py, pyro/util/runparams.py, setup.py
I changed setup.py to install an autogenerated shim script that loads pyro.pyro_sim as a module, as otherwise `__file__` would point to the bin directory it gets installed to, rather than the pyro/ directory.
With a minor change to test.py, this lets us run the regression tests from outside pyro/ as well.
=> Allow running pyro_sim.py from anywhere

pyro/advection/simulation.py, pyro/advection_nonuniform/simulation.py, pyro/compressible/simulation.py, pyro/compressible_react/simulation.py, pyro/compressible_sr/simulation.py, pyro/diffusion/simulation.py, pyro/incompressible/simulation.py, pyro/lm_atm/simulation.py, pyro/mesh/tests/test_patch.py, pyro/swe/simulation.py
`mpl_toolkits.legacy_colorbar = False` is a no-op as of matplotlib 3.4
=> Resolve deprecation warnings

pyro/util/plot_tools.py
Effectively does the same thing as hitting Ctrl+C in the terminal, but doesn't require fighting for focus with the matplotlib window.
=> Allow exiting with Ctrl+C when visualization is on

pyro/analysis/gauss_diffusion_compare.py, pyro/analysis/sedov_compare.py, pyro/mesh/array_indexer.py
=> np.int is deprecated in np.1.20

pyproject.toml, pyro/advection/simulation.py, pyro/advection_nonuniform/simulation.py, pyro/analysis/convergence.py, pyro/analysis/dam_compare.py, pyro/analysis/gauss_diffusion_compare.py, pyro/analysis/incomp_converge_error.py, pyro/analysis/sedov_compare.py, pyro/analysis/smooth_error.py, pyro/analysis/sod_compare.py, pyro/compressible_react/simulation.py, pyro/compressible_sr/c2p.py, pyro/incompressible/incomp_interface.py, pyro/incompressible/simulation.py, pyro/lm_atm/LM_atm_interface.py, pyro/lm_atm/simulation.py, pyro/multigrid/MG.py, pyro/multigrid/general_MG.py, pyro/multigrid/variable_coeff_MG.py, pyro/particles/particles.py, pyro/simulation_null.py, pyro/test.py, pyro/util/io_pyro.py, pyro/util/runparams.py
Fix a spurious divide-by-zero error in sedov_compare.py and gauss_diffusion_compare.py that pylint found. Most of the other fixes are for `unused-variable`, plus some instances of `consider-using-enumerate`, `consider-using-dict-items`, `consider-iterating-dictionary`, `use-dict-literal`, `useless-object-inheritance`, and `unneeded-not`.
Also disable `pointless-string-statement`, since these are used for block comments in a couple places.
=> Fix more pylint warnings

.coveragerc, .github/workflows/docs-test.yml, .github/workflows/flake8.yml, .github/workflows/gh-pages.yml, .github/workflows/isort.yml, .github/workflows/pylint.yml, .github/workflows/pytest.yml, .github/workflows/regtest.yml, setup.py
Add coverage config file and install pyro with pip instead of running setup.py directly
=> Pick up new benchmarks automatically and improve github actions

.flake8, .github/workflows/pylint.yml, logo/logo.py, pyproject.toml, pyro/advection/tests/test_advection.py, pyro/advection_nonuniform/tests/test_advection_nonuniform.py, pyro/compressible/tests/test_compressible.py, pyro/compressible/tests/test_eos.py, pyro/compressible_rk/tests/test_compressible_rk.py, pyro/compressible_sr/tests/test_compressible_sr.py, pyro/compressible_sr/tests/test_eos_sr.py, pyro/diffusion/tests/test_diffusion.py, pyro/incompressible/tests/convergence_errors.py, pyro/mesh/tests/test_array_indexer.py, pyro/mesh/tests/test_io.py, pyro/mesh/tests/test_patch.py, pyro/multigrid/tests/test_multigrid_comps.py, pyro/particles/tests/test_particles.py, pyro/swe/tests/test_swe.py, pyro/tests/test_pyro.py, pyro/tests/test_simulation.py, pyro/util/tests/test_runparams.py
Adds short descriptions for all the ignored flake8 error codes.
W291 (trailing whitespace) is no longer ignored and F401 (module imported but unused) is only ignored for `__init__.py` files.
=> Clean up pylint warnings in unit tests and update flake8 config

.github/workflows/pylint.yml, pyproject.toml, pyro/advection_fv4/fluxes.py, pyro/advection_fv4/simulation.py, pyro/advection_rk/fluxes.py, pyro/advection_rk/simulation.py, pyro/advection_weno/fluxes.py, pyro/advection_weno/simulation.py, pyro/burgers/advective_fluxes.py, pyro/burgers/problems/smooth.py, pyro/burgers/problems/test.py, pyro/burgers/problems/tophat.py, pyro/burgers/problems/verify.py, pyro/burgers/simulation.py, pyro/compressible/interface.py, pyro/compressible_fv4/fluxes.py, pyro/compressible_fv4/simulation.py, pyro/compressible_sr/interface.py, pyro/compressible_sr/unsplit_fluxes.py, pyro/swe/interface.py, pyro/swe/simulation.py, pyro/swe/tests/test_swe.py, pyro/swe/unsplit_fluxes.py
This resolves the remaining pylint warnings and enables warnings for the CI action.
=> Final pylint cleanup

README.md, docs/source/multigrid_basics.rst, docs/source/notes.rst
we split up the old notebook, so this points to the basic example now
=> change link to multigrid notebook

pyro/viscous_burgers/simulation.py
Override the initialize() method because it was initializing problems in burgers instead of viscous_burgers, (although the problems are the same...)
=> fix viscous burgers problem initialization issue

pyro/mesh/mesh-examples.ipynb
Python 3.11.7 and 3.12.1 removed the `(if defined)` notice on `__dict__` and `__weakref__`.
=> Skip checking the output of `help()` in a notebook

.github/workflows/pytest.yml, README.md, docs/source/testing.rst, examples/mesh/experiments/test_indexer.py, examples/mesh/experiments/test_mask.py, examples/mesh/experiments/test_subclass.py, presentations/pyro_intro.ipynb, pyproject.toml
* fix some old code under `examples/mesh/experiments` that was breaking pytest discovery
* update `presentations/pyro_intro.ipynb` to the new package layout and ignore a cell that prints its run time
* move the pytest ignores to pyproject.toml
This allows us to simply run `pytest` from the repository root, and not have to pass a bunch of `--ignore` arguments.
=> Simplify pytest usage

examples/mesh/bc_demo.py, pyro/mesh/patch.py, pyro/util/io_pyro.py
this allows us to plot the output again
=> store coord_type in the output file + fix reading

pyro/advection/simulation.py, pyro/advection_nonuniform/simulation.py, pyro/compressible/simulation.py, pyro/compressible_react/simulation.py, pyro/diffusion/simulation.py, pyro/swe/simulation.py
the colorbar's were not showing the data values
this reverts some of 86f4aadfae28e9c50f7ec98a7fee777d6fb068d8
=> fix the colorbar tick labels in plots

pyro/compressible/problems/_gresho.defaults, pyro/compressible/problems/gresho.py, pyro/compressible/problems/inputs.gresho
this is in line with the version from Miczek, Ropke, and Edelmann
=> sync the gresho problem up with Castro

pyro/compressible_sdc/_defaults
this silences a warning and will be needed once we hook in the exact Riemann solver
=> add the riemann option to compressible_sdc

pyro/mesh/array_indexer.py
I found this when running `examples/mesh/bc_demo.py`.
=> Fix type check when pretty printing integer data

docs/source/running.rst
we've changed how parameters work since this was last updated.
=> update the docs on running Pyro

pyro/compressible/riemann.py
this follows Minioshima & Miyoshi (2021) to get the correct asymptotic pressure behavior at low Mach numbers
=> add an implementation of an HLLC solver with low Mach corrections

pyro/mesh/patch.py, pyro/mesh/tests/test_patch.py
adds dloga in grid, mainly used for primitive geometric terms later
=> add dloga in grid

pyro/compressible/unsplit_fluxes.py
during calculation of the interface state, we should only apply pressure gradient to the momentum in the transverse direction since the normal direction momentum is already includes pressure term during reconstruction.
=> Fix transverse pres gradient for spherical geometry.

pyro/compressible/problems/inputs.rt_multimode, pyro/compressible/problems/rt_multimode.py
This seems to work with both `compressible` and `compressible_fv4`.
=> add a multimode RT problem

pyro/compressible/problems/convection.py
we use a random velocity field at initialization
this makes the problem reproducible
=> use a seeded random number generator for convection

pyro/compressible/__init__.py, pyro/compressible/_defaults, pyro/compressible/simulation.py, pyro/compressible_fv4/_defaults, pyro/compressible_fv4/simulation.py, pyro/compressible_rk/_defaults, pyro/compressible_rk/simulation.py, pyro/compressible_sdc/_defaults
for the CTU solver, the sponge update is implicit in time
for the RK/SDC solvers, it is an explicit source
this damps the velocity field over a timescale "sponge_timescale"
The sponge is essentially the same as in Castro
=> implement a sponge term in compressible

pyro/compressible/derives.py, pyro/util/io_pyro.py
previously, if the solver itself did not define derives.py, then we didn't add any derived variables.  But compressible uses a lot of inheritance, and only the base compressible has derives.py. Now we loop over the inheritance hierarchy and try importing derives until we find it.
Also add machnumber to the compressible derives
=> fix how derives are imported when reading output

pyro/compressible_fv4/simulation.py
we can use the version we inherit
=> compressible_fv4 does not need to reimplement evolve

pyro/compressible/simulation.py, pyro/compressible_fv4/simulation.py, pyro/compressible_rk/simulation.py
I forgot to include the kinetic energy source
=> [WIP] fix the sponge source

pyro/compressible/problems/inputs.convection.big
this is now periodic on the sides
adds a small_dens
and a new inputs that is twice as wide
=> update convection inputs

.codespellrc, .github/workflows/codespell.yml, docs/source/adding_a_problem_jupyter.ipynb, docs/source/rt_average.ipynb
this will preprocess the notebooks and remove the output first
=> run codespell on notebooks
